# Project information
site_name: alxx.nl
site_url: https://alxx.nl
site_author: Alex van den Hoogen
site_description: >
  Compilation of my persondal documentation about Home Assistant, my homelab
  and other interesting things.

# Repository
repo_name: alex3305/docs
repo_url: https://github.com/alex3305/docs

# Copyright
copyright: Copyright &copy; 2020 - 2023 Alex van den Hoogen

# Configuration
theme:
  name: material
  custom_dir: .overrides

  icon:
    logo: fontawesome/solid/pepper-hot

  palette: 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: amber
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: amber 
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  font:
    text: Source Sans Pro
    code: Source Code Pro

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables
  - pymdownx.highlight
  - pymdownx.superfences 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Plugins
plugins:
  - search
