# Project information
site_name: alxx.nl
# site_url: https://docs.alxx.nl
site_author: Alex van den Hoogen
site_description: >
  Compilation of my persondal documentation about Home Assistant, my homelab
  and other interesting things.

# Repository
repo_name: alex3305/docs
repo_url: https://github.com/alex3305/docs

# Copyright
copyright: Copyright &copy; 2020 - 2023 Alex van den Hoogen

# Configuration
theme:
  name: material
  custom_dir: .overrides

  icon:
    logo: fontawesome/solid/pepper-hot

  palette: 
    scheme: slate
    primary: purple
    accent: amber 
  
  font:
    text: Source Sans Pro
    code: Source Code Pro

  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - tables

# Plugins
plugins:
  - search
